# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: pre-release

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        distro: [humble, rolling]

    env:
      ROS_DISTRO: ${{ matrix.distro }}
      TEST: debian's
      BASEDIR: ${{ github.workspace }}/.work

    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: industrial_ci
        uses: ros-industrial/industrial_ci@master

      - name: find debian
        run: find . -name ros-rolling-rsl_0.2.0-ici~jammy_amd64.deb

      - name: show files here
        run: tree .

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3

        with:
          name: my-artifact
          path: ros-rolling-rsl_0.2.0-ici~jammy_amd64.deb
          retention-days: 5
